# Generated by Django 5.0.4 on 2024-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('image', models.ImageField(upload_to='media')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
